version: '3.1'

services:

    container_1_1:
      image: httpd:2.4
      networks:
        - reseaux_1
      ports:
        - 127.0.0.1:8081:80


    container_1_2: 
      image: nginx
      networks:
        - reseaux_1

    containter_2_1:
      image: httpd:2.4
      networks:
        - reseaux_2


    container_2_2: 
      image: nginx
      networks:
        - reseaux_2


networks:
  reseaux_1:
  reseaux_2: