version: '3.1'

services:
  
  # Service de base de donnée mysql
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: stevy
      MYSQL_PASSWORD: toor

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: stevy
      MYSQL_PASSWORD: toor

  php:
    build: ./
    links:
      - db
    ports:
      - 80:80
    volumes:
      - /src:/var/www/html