---
  - name: my-play
    hosts: all
    become: true
    tasks:
      - name: Create testdir directory
        ansible.builtin.file:
          path: /testdir
          state: directory
          mode: '0777'