---
  - name: my-play
    hosts: all
    vars:
      - username: stevy
      - home: /home/stevy
    tasks:
      - name: Create testdir directory
        ansible.builtin.file:
          path: /testdir
          state: directory
          mode: '0777'
      - name: print all facts 
        ansible.builtin.debug:
          var: ansible_facts