---
- name: Create others host file
  file:
    path: "{{ ansible_user_dir }}/others_hosts"
    state: touch
  when: inventory_hostname == last_item


- name: Get others host without mine
  copy:
    content: | 
        Ip List 
        {{ hostvars[item].ansible_host }}
    dest: "{{ ansible_user_dir }}/others_hosts"
  loop: "{{ groups.all }}"
  when: "inventory_hostname == last_item and ansible_host != hostvars[item].ansible_host"
