name: CI/CD 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on : ${{ matrix.os }}

    strategy:
      matrix:
        php-version : 
          - 7.4
          - 8.1
        os:
          - ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with: 
         php-version : ${{ matrix.php-version}}
      - name: Test php 
        run: php --version
    